### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-expressive-router#10]
Hi,

I love the flexibility zend-expressive-router has brought into the routing world. But on the other hand it introduces / remove some of the features of each router which brings some problems also.

Eg : 

We cannot quickly move from `FastRoute` to `AuraRouter` and vice versa. The problem is due to the path can accept regular expression for FastRoute , but not for Aura. This is actually good for FastRoute, but Aura.Router missed some features we could make use of. I believe this is true for any router which can be configured other than via the path.

A recent example is 

```php
$router->add('aura.asset', '/asset/{vendor}/{package}/{file}')
    ->setValues([
        'action' => 'aura.asset',
    ])
    ->addTokens(array(
        'file' => '(.*)'
    ));
```

which can be written in FastRoute as `/asset/{vendor}/{package}/{file:.*}` . So I guess there need a parser also.

**Comment by michaelmoussa** [comment]
@harikt I think this is going to be the case for any "mostly-interchangeable" component. You can't move from `FastRoute` to `AuraRouter` "quickly", but you will also have challenges moving between `Aura.Di`, Zend ServiceManager, and Pimple. The same goes for Twig/Plates/zend-view, or any similar component for that matter.

The objective of the Zend Expressive routing integrations is to allow you to choose to use your favorite router from the choices we offer and take advantage of its capabilities, but _not necessarily_ to make all of the routers work the same.

If `AuraRouter` doesn't support routing via regex, that's functionality that should be implemented either in `AuraRouter` or via some kind of plugin library that will turn regex configured routes into something that `AuraRouter` can understand. In either case, that's something that could be _used_ by Expressive, but not written as part of Expressive.

Is that about right @weierophinney, or do you want to add anything?

**Comment by harikt** [comment]
@michaelmoussa you are correct. But I was thinking if the [Zend\Expressive\Route](https://github.com/zendframework/zend-expressive-router/blob/7e624edc4da2306ff12dfb69c7fadf44efa567f1/src/Route.php) have some features it may be useful for https://github.com/zendframework/zend-expressive-aurarouter , https://github.com/zendframework/zend-expressive-fastrouter etc to switch.

So people can consider writing as 

```php
new Route('/', ...)
```

Thank you

**Comment by michaelmoussa** [comment]
I'm not sure I understand. (but I want to!) Can you you give me an example?

You can provide additional configuration options to each route, which the router bridges can use [like this](https://github.com/zendframework/zend-expressive-aurarouter/blob/57ed2c17b90c0fcb23aabe03872a14c89ed8325c/src/AuraRouter.php#L202-L211).

So looking at your example in your first comment, this:

```php
$router->add('aura.asset', '/asset/{vendor}/{package}/{file}')
    ->setValues([
        'action' => 'aura.asset',
    ])
    ->addTokens(array(
        'file' => '(.*)'
    ));
```

could be represented as a `Route` in the form below (_not tested_):

```php
$route = new Route(
    '/asset/{vendor}/{package}/{file}',
    <... some middleware ...>,
    Route::HTTP_METHOD_ANY,
    'aura.asset'
);
$route->setOptions([
    'values' => ['action' => 'aura.asset'],
    'tokens' => 'file' => '(.*)'
]);
```

If you wanted to switch to `FastRoute`, the _exact_ route code above wouldn't work obviously since `FastRoute` won't know what to do with `values` or `tokens` in the options, but in the case of `FastRoute` you can just use a regex.

So yes, there is _some_ effort required in changing from one routing library to another, but that's unavoidable. If you have any more specific suggestions on what we could do to make that easier without making `Zend\Expressive\Router\Route` need to know too much about which specific routing libraries are being used, then we can go from there.

At this time though, I don't think that completely switching from one routing mechanism to another in a mature application is a common enough use case that the tools we have available right now would make it unreasonably difficult to do so.

**Comment by harikt** [comment]
I agree with your comments @michaelmoussa . It will be hard / not worth to implement . Else we probably need a common way for `path` how it could be defined.

Thanks for your time. I appreciate you looking into this.

**Comment by michaelmoussa** [comment]
No problem. Glad to help!

**Comment by xtreamwayz** [comment]
To clarify this a bit more: the routers their selves take care of handling the routes. It's given the config through zend-expressive-router. However zend-expressive-router cannot magically add functionality from zend-router to aura-router. The only exception is zend-router-fastroute which handles route generation since FastRoute itself doesn't do this.

Same goes for the containers. zend-servicemanager is a lot more powerful than the other containers. However in that case the config for zend-servicemanager was chosen and with some tricks in the ./config/config.php (from the skeleton) the main parts of the container config (factories and invokables) are translated for the other containers. But features like the abstract factory can not be added magically to the other containers.

The best example I can give you is with template renderers. They all are completely different and there is no way to interchange these. Because that is basically what you are asking (although for the routes): make the templates from twig, plates and zend-view interchangeable.
I know you might think now that you asked for interchangeable config and not templates, but for the routers the path is what templates are for the renderers. It's their core functionality. 

I hope this makes sense and clarifies why it would cause too much overhead, is nearly impossible and (IMHO) not really worth it.

If you want functionality from another router added to your current router, I think the best way to do that is by sending PR's to those routers. The same goes for containers and template renderers.
